version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-user1-dev-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qtl95tb0hf9t"
s3_prefix = "sam-app-user1-dev-stack"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
